language: python

services:
  - docker

python:
  - "3.7"

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install pytest-cov

install:
  - pip install -r requirements.txt

before_script:
  - pytest -ra --cov=black_scholes --ignore smoke_tests

script:
  - docker-compose up --build --abort-on-container-exit

after_script:
  - docker-compose down --rmi all
