version: '3'
services:
  web:
    build: ./black_scholes
    ports:
      - "5000:5000"
  smoke_test:
    build: ./smoke_tests
    command: sh -c 'dockerize -wait http://host.docker.internal:5000 -- pytest -ra'