swagger: "2.0"
info:
  description: This is the swagger file that describes the API for our Black-Scholes Option Calculator
  version: "1.0.0"
  title: Black-Scholes Option Calculator
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /call_calculator:
    get:
      operationId: calculator.calculate_call_option_price
      tags:
        - calculator
      description: Calculates the price of a call option using the Black-Scholes option pricing model
      parameters:
      - name: strike_price
        description: the strike price of the option
        in: query
        type: number
        format: double
      - name: option_maturity_years
        description: the time from now until the maturity of the option expressed in years
        in: query
        type: number
        format: double
      - name: current_price
        description: the current price of the underlying
        in: query
        type: number
        format: double
      - name: volatility_percent
        description: the volatility of the underlying, expressed as a percentage
        in: query
        type: number
        format: double
      - name: risk_free_rate_percent
        description: the risk free interest rate, expressed as a percentage
        in: query
        type: number
        format: double
      responses:
        200:
          description: Successful calculation of option price
          schema:
            type: number
            format: double
  /put_calculator:
    get:
      operationId: calculator.calculate_put_option_price
      tags:
        - calculator
      description: Calculates the price of a put option using the Black-Scholes option pricing model
      parameters:
      - name: strike_price
        description: the strike price of the option
        in: query
        type: number
        format: double
      - name: option_maturity_years
        description: the time from now until the maturity of the option expressed in years
        in: query
        type: number
        format: double
      - name: current_price
        description: the current price of the underlying
        in: query
        type: number
        format: double
      - name: volatility_percent
        description: the volatility of the underlying, expressed as a percentage
        in: query
        type: number
        format: double
      - name: risk_free_rate_percent
        description: the risk free interest rate, expressed as a percentage
        in: query
        type: number
        format: double
      responses:
        200:
          description: Successful calculation of option price
          schema:
            type: number
            format: double