swagger: "2.0"
info:
  description: This is the swagger file that describes the API for our Black-Scholes Option Calculator
  version: "1.0.0"
  title: Black-Scholes Option Calculator
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /calculator:
    post:
      operationId: calculator.calculate_option_price
      tags:
        - calculator
      description: Calculates the price of an option using the Black-Scholes option pricing model
      parameters:
      - in: body
        name: model_inputs
        description: The inputs into the Black-Scholes option pricing model
        schema:
          type: object
          required:
          - call_put
          - strike_price
          - option_maturity_years
          - current_price
          - volatility_percent
          - risk_free_rate_percent
          properties:
            call_put:  
              type: string
            strike_price:
              type: number
              format: double
            option_maturity_years:
              type: number
              format: double
            current_price:
              type: number
              format: double
            volatility_percent:
              type: number
              format: double
            risk_free_rate_percent:
              type: number
              format: double
      responses:
        200:
          description: Successful calculation of option price
          schema:
            type: number
            format: double